[log]
level = "info"

[cluster]
name = "tidb-test"
plugin = ""

[mysql]
host = "10.2.103.202"
port = "5000"
user = "root"
password = ""

[ssh]
user = "tidb"
sshPort = "22"

[load]
cmd = ""
interval = 0
sleep = 10

[other]
dir = "/Users/yuyang/go/src/pictorial/other"

